/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.sidoh.wwf_api.types.game_state;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BoardStorage implements org.apache.thrift.TBase<BoardStorage, BoardStorage._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BoardStorage");

  private static final org.apache.thrift.protocol.TField SLOTS_FIELD_DESC = new org.apache.thrift.protocol.TField("slots", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BoardStorageStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BoardStorageTupleSchemeFactory());
  }

  /**
   * A list of all of the slots available for play
   */
  public List<Slot> slots; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * A list of all of the slots available for play
     */
    SLOTS((short)1, "slots");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SLOTS
          return SLOTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SLOTS, new org.apache.thrift.meta_data.FieldMetaData("slots", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Slot.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BoardStorage.class, metaDataMap);
  }

  public BoardStorage() {
  }

  public BoardStorage(
    List<Slot> slots)
  {
    this();
    this.slots = slots;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BoardStorage(BoardStorage other) {
    if (other.isSetSlots()) {
      List<Slot> __this__slots = new ArrayList<Slot>();
      for (Slot other_element : other.slots) {
        __this__slots.add(new Slot(other_element));
      }
      this.slots = __this__slots;
    }
  }

  public BoardStorage deepCopy() {
    return new BoardStorage(this);
  }

  @Override
  public void clear() {
    this.slots = null;
  }

  public int getSlotsSize() {
    return (this.slots == null) ? 0 : this.slots.size();
  }

  public java.util.Iterator<Slot> getSlotsIterator() {
    return (this.slots == null) ? null : this.slots.iterator();
  }

  public void addToSlots(Slot elem) {
    if (this.slots == null) {
      this.slots = new ArrayList<Slot>();
    }
    this.slots.add(elem);
  }

  /**
   * A list of all of the slots available for play
   */
  public List<Slot> getSlots() {
    return this.slots;
  }

  /**
   * A list of all of the slots available for play
   */
  public BoardStorage setSlots(List<Slot> slots) {
    this.slots = slots;
    return this;
  }

  public void unsetSlots() {
    this.slots = null;
  }

  /** Returns true if field slots is set (has been assigned a value) and false otherwise */
  public boolean isSetSlots() {
    return this.slots != null;
  }

  public void setSlotsIsSet(boolean value) {
    if (!value) {
      this.slots = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SLOTS:
      if (value == null) {
        unsetSlots();
      } else {
        setSlots((List<Slot>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SLOTS:
      return getSlots();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SLOTS:
      return isSetSlots();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BoardStorage)
      return this.equals((BoardStorage)that);
    return false;
  }

  public boolean equals(BoardStorage that) {
    if (that == null)
      return false;

    boolean this_present_slots = true && this.isSetSlots();
    boolean that_present_slots = true && that.isSetSlots();
    if (this_present_slots || that_present_slots) {
      if (!(this_present_slots && that_present_slots))
        return false;
      if (!this.slots.equals(that.slots))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(BoardStorage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    BoardStorage typedOther = (BoardStorage)other;

    lastComparison = Boolean.valueOf(isSetSlots()).compareTo(typedOther.isSetSlots());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSlots()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.slots, typedOther.slots);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BoardStorage(");
    boolean first = true;

    sb.append("slots:");
    if (this.slots == null) {
      sb.append("null");
    } else {
      sb.append(this.slots);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (slots == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'slots' was not present! Struct: " + toString());
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BoardStorageStandardSchemeFactory implements SchemeFactory {
    public BoardStorageStandardScheme getScheme() {
      return new BoardStorageStandardScheme();
    }
  }

  private static class BoardStorageStandardScheme extends StandardScheme<BoardStorage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BoardStorage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SLOTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.slots = new ArrayList<Slot>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  Slot _elem10; // required
                  _elem10 = new Slot();
                  _elem10.read(iprot);
                  struct.slots.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setSlotsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BoardStorage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.slots != null) {
        oprot.writeFieldBegin(SLOTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.slots.size()));
          for (Slot _iter11 : struct.slots)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BoardStorageTupleSchemeFactory implements SchemeFactory {
    public BoardStorageTupleScheme getScheme() {
      return new BoardStorageTupleScheme();
    }
  }

  private static class BoardStorageTupleScheme extends TupleScheme<BoardStorage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BoardStorage struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.slots.size());
        for (Slot _iter12 : struct.slots)
        {
          _iter12.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BoardStorage struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.slots = new ArrayList<Slot>(_list13.size);
        for (int _i14 = 0; _i14 < _list13.size; ++_i14)
        {
          Slot _elem15; // required
          _elem15 = new Slot();
          _elem15.read(iprot);
          struct.slots.add(_elem15);
        }
      }
      struct.setSlotsIsSet(true);
    }
  }

}

