/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.sidoh.wwf_api.types.game_state;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum SlotModifier implements org.apache.thrift.TEnum {
  NONE(0),
  DOUBLE_LETTER(1),
  DOUBLE_WORD(2),
  TRIPLE_LETTER(3),
  TRIPLE_WORD(4);

  private final int value;

  private SlotModifier(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SlotModifier findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return DOUBLE_LETTER;
      case 2:
        return DOUBLE_WORD;
      case 3:
        return TRIPLE_LETTER;
      case 4:
        return TRIPLE_WORD;
      default:
        return null;
    }
  }
}
