/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.sidoh.wwf_api.types.api;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MoveType implements org.apache.thrift.TEnum {
  RESIGN(1),
  PLAY(2),
  SWAP(3),
  PASS(4),
  DECLINE(5),
  GAME_OVER(6),
  TIE(7);

  private final int value;

  private MoveType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static MoveType findByValue(int value) { 
    switch (value) {
      case 1:
        return RESIGN;
      case 2:
        return PLAY;
      case 3:
        return SWAP;
      case 4:
        return PASS;
      case 5:
        return DECLINE;
      case 6:
        return GAME_OVER;
      case 7:
        return TIE;
      default:
        return null;
    }
  }
}
