/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.sidoh.wwf_api.types.api;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Search can either be facebook or zynga user id
 */
public class SearchGameParams extends org.apache.thrift.TUnion<SearchGameParams, SearchGameParams._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SearchGameParams");
  private static final org.apache.thrift.protocol.TField ZYNGA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("zyngaId", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField FB_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("fbId", org.apache.thrift.protocol.TType.I64, (short)2);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ZYNGA_ID((short)1, "zyngaId"),
    FB_ID((short)2, "fbId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ZYNGA_ID
          return ZYNGA_ID;
        case 2: // FB_ID
          return FB_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ZYNGA_ID, new org.apache.thrift.meta_data.FieldMetaData("zyngaId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FB_ID, new org.apache.thrift.meta_data.FieldMetaData("fbId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SearchGameParams.class, metaDataMap);
  }

  public SearchGameParams() {
    super();
  }

  public SearchGameParams(_Fields setField, Object value) {
    super(setField, value);
  }

  public SearchGameParams(SearchGameParams other) {
    super(other);
  }
  public SearchGameParams deepCopy() {
    return new SearchGameParams(this);
  }

  public static SearchGameParams zyngaId(long value) {
    SearchGameParams x = new SearchGameParams();
    x.setZyngaId(value);
    return x;
  }

  public static SearchGameParams fbId(long value) {
    SearchGameParams x = new SearchGameParams();
    x.setFbId(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, Object value) throws ClassCastException {
    switch (setField) {
      case ZYNGA_ID:
        if (value instanceof Long) {
          break;
        }
        throw new ClassCastException("Was expecting value of type Long for field 'zyngaId', but got " + value.getClass().getSimpleName());
      case FB_ID:
        if (value instanceof Long) {
          break;
        }
        throw new ClassCastException("Was expecting value of type Long for field 'fbId', but got " + value.getClass().getSimpleName());
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case ZYNGA_ID:
          if (field.type == ZYNGA_ID_FIELD_DESC.type) {
            Long zyngaId;
            zyngaId = iprot.readI64();
            return zyngaId;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case FB_ID:
          if (field.type == FB_ID_FIELD_DESC.type) {
            Long fbId;
            fbId = iprot.readI64();
            return fbId;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case ZYNGA_ID:
        Long zyngaId = (Long)value_;
        oprot.writeI64(zyngaId);
        return;
      case FB_ID:
        Long fbId = (Long)value_;
        oprot.writeI64(fbId);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case ZYNGA_ID:
          Long zyngaId;
          zyngaId = iprot.readI64();
          return zyngaId;
        case FB_ID:
          Long fbId;
          fbId = iprot.readI64();
          return fbId;
        default:
          throw new IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      return null;
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case ZYNGA_ID:
        Long zyngaId = (Long)value_;
        oprot.writeI64(zyngaId);
        return;
      case FB_ID:
        Long fbId = (Long)value_;
        oprot.writeI64(fbId);
        return;
      default:
        throw new IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case ZYNGA_ID:
        return ZYNGA_ID_FIELD_DESC;
      case FB_ID:
        return FB_ID_FIELD_DESC;
      default:
        throw new IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public long getZyngaId() {
    if (getSetField() == _Fields.ZYNGA_ID) {
      return (Long)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'zyngaId' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setZyngaId(long value) {
    setField_ = _Fields.ZYNGA_ID;
    value_ = value;
  }

  public long getFbId() {
    if (getSetField() == _Fields.FB_ID) {
      return (Long)getFieldValue();
    } else {
      throw new RuntimeException("Cannot get field 'fbId' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setFbId(long value) {
    setField_ = _Fields.FB_ID;
    value_ = value;
  }

  public boolean isSetZyngaId() {
    return setField_ == _Fields.ZYNGA_ID;
  }


  public boolean isSetFbId() {
    return setField_ == _Fields.FB_ID;
  }


  public boolean equals(Object other) {
    if (other instanceof SearchGameParams) {
      return equals((SearchGameParams)other);
    } else {
      return false;
    }
  }

  public boolean equals(SearchGameParams other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(SearchGameParams other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  /**
   * If you'd like this to perform more respectably, use the hashcode generator option.
   */
  @Override
  public int hashCode() {
    return 0;
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
